### PR TITLE
Propose Update to Manifest - 'broken links to -trunkbaseddevelopment.com'

### PR DESCRIPTION
**Pull request by pescadorbob**
# Description

Upon further reading and clicking links, I found a few links that were broken links, where it had been switched from trunkbaseddevlopment.com to a local page, but the local page wasn't in this repo.

Fixes # 331

## Type of change

- [x] Propose Update to Manifesto

### CODE REVIEW

**Comment by pescadorbob** [comment]
I saw this failure:
crawling ./public
[0] https://trunkbaseddevelopment.com/
[0] https://www.branchbyabstraction.com/
public/minimumcd/tbd/
  [0] https://trunkbaseddevelopment.com/
public/minimumcd/ci/
  [0] https://www.branchbyabstraction.com/
ERROR: Detected 2 broken links. Scanned 101 links in 2.868 seconds.
Error: Process completed with exit code 1.
which doesn't appear when I run `npm test` locally.
but I'm guessing it has to do with the certs on the target site:
image
When you click those links, it comes up with a warning.

**Comment by pescadorbob** [comment]
Does anyone of the contributors have contacts with the contributors of trunk based development to inform them that their certs are invalid?

**Comment by pescadorbob** [comment]
Looks like the SAN is incorrect:
image

**Comment by bdfinst** [comment]
Paul Hammant is the maintainer. I can tweet at him. I'm not seeing issues with the certs when I checked just now. What are you seeing?

**Comment by pescadorbob** [comment]
As well as the CN:
image

**Comment by bdfinst** [comment]
I make bad middleware though. His tag is @paul_hammant if you want to tweet at him.

**Review by bdfinst — APPROVED** [review]

**Comment by pescadorbob** [comment]
I created an issue in his repo here: https://github.com/paul-hammant/tbd/issues/109

**Comment by pescadorbob** [comment]
> Paul Hammant is the maintainer. I can tweet at him. I'm not seeing issues with the certs when I checked just now. What are you seeing?

See the error at the top of the thread. The pipeline sees the error as well. You may have warnings for this site disabled on your machine.

**Comment by bdfinst** [comment]
I've not submitted a PR myself for a while. I'll double-check the pre-commit hooks. Did you add yourself as a contributor?

**Comment by pescadorbob** [comment]
It may also be important to note that when these broken links were introduced by @bdfinst and @DevOpsCraftsman , I'm not sure if you saw the error, or why you switched those links. I'm guessing there was a precommit hook fired and you just switched the link to link something right in this repo, but there is no content for it in this repo. However - the pre-commit link checker allows for bad links as long as they are right here in this repo with an anchor tag. :)
Can you think of a better test that would have caught this?
In doing a search, I see a couple other places where this occurred:
content/References/_index.md e.g.

**Comment by pescadorbob** [comment]
I didn't add myself as a contributor. but I'll do it.

**Comment by bdfinst** [comment]
Please do and thanks for the debug. I'll check the test ASAP. that definitely explains why it didn't show up locally or in CI.

**Pull request merged**
