### PR TITLE
Propose Update to Manifesto - Add test env content

### PR DESCRIPTION
**Pull request by nbeck415**
# Description
- This enables the **Prod-Like Test Env** pages and includes content about staging and ephemeral environments
- This adds EphemeralEnvironments.io link to the homepage
- Add self to signatories and contributors

Fixes # (issue)
#358

## Type of change
Changes to supporting information

Please delete the option that is not relevant.

- [x] Signature (please update title to "Signature 'your name'")
- [x] Propose Update to Manifesto (please update title to "Propose Update to Manifesto - 'update description'")

Please close this and let me know if I should create a separate PR for my signature.

### CODE REVIEW

**Comment by ferrix** [comment]
Adding ephemeral environments to the front page is not going to be fine to all the signatories. There are other ways to have production-like test environments and ephemeral is neither possible nor required in all situations. The goal of MinimumCD is to be applicable to software engineering in general. 

Example:

When hardware is concerned, the pipeline may consist of proprietary physical test fixtures that cannot be ephemeral.

**Comment by bdfinst** [comment]
Sorry for the delay, I've been taking a break over the holidays.

I agree with @ferrix that ephemeral environments are an example of an implementation, but not true in every context. For example, firmware pipelines often contain real hardware.

I suggest having the main page link to the "Prod Like" page and have that page describe ephemeral environments as an example implementation with a link to ephemeralenvironments.io.

**Review by bdfinst — CHANGES_REQUESTED** [review]
Sorry for the delay, I've been taking a break over the holidays.

I agree with @ferrix that ephemeral environments are an example of an implementation, but not true in every context. For example, firmware pipelines often contain real hardware.

I suggest having the main page link to the "Prod Like" page and have that page describe ephemeral environments as an example implementation with a link to ephemeralenvironments.io.

**Review by bdfinst — APPROVED** [review]
LGTM

**Pull request merged**
